title: Users
modelClass: TheOne74\Telegram\Models\User
list: $/theone74/telegram/models/user/columns.yaml
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
showSorting: 1
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
