plugin:
    name: 'theone74.telegram::lang.plugin.name'
    description: 'theone74.telegram::lang.plugin.description'
    author: 'Anton R'
    icon: icon-paper-plane-o
    homepage: ''
navigation:
    main-menu-item:
        label: 'theone74.telegram::lang.plugin.name'
        url: theone74/telegram/users
        icon: icon-paper-plane
        sideMenu:
            side-menu-item:
                label: 'theone74.telegram::lang.left_menu.users'
                url: theone74/telegram/users
                icon: icon-user
            side-menu-item2:
                label: 'theone74.telegram::lang.left_menu.messages'
                url: theone74/telegram/messages
                icon: icon-file-text
            side-menu-item3:
                label: 'theone74.telegram::lang.left_menu.chats'
                url: theone74/telegram/chats
                icon: icon-comments
